///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/game.aks
/// Generation time: mar oct 31 23:48:53 CET 2017
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x0040
#define song_ingame_size     369
#define song_ingame_end      0x1B1

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
